name: Fetch
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 4 * * *' # Every day at 04:00 UTC+0
    # If it only gets uploaded on Monday
    # make sure to get it
    - cron: '0 6 * * 1' # Monday at 06:00 UTC+0
    - cron: '0 8 * * 1' # Monday at 08:00 UTC+0

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run
        run: yarn start

      - name: Get current date and tme
        id: date
        run: echo "date=$(date +"%Y-%m-%d %H:%M" --utc)" >> $GITHUB_OUTPUT

      - name: Copy data
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
          publish_branch: data
          keep_files: true
          full_commit_message: ${{ steps.date.outputs.date }}
